---
# ============================================================
# konfiguracni promenne pro corosync a pacemaker

master_server: 'r1nren.et.cesnet.cz'
corosync_cluster_name: 'eduroam.cz'
pacemaker_group_name: 'group_eduroam.cz'

# ============================================================
# konfigurace clusteru

# ============================================================
# konfigurace zdroju

# manualni smazani konfigurace celeho clusteru:
# cibadmin -E --force
#
# pri zmene parametru neni vytvoren novy zdroj s jinymi parametry,
# ale je nutne ho nejdriv manualne smazat prikazem 'cibadmin -E --force'!
#
#
# For example, a setting of migration-threshold=2 and failure-timeout=60s 
# would cause the resource to move to a new node after 2 failures, 
# and allow it to move back (depending on stickiness and constraint scores) after one minute.

pacemaker_cluster_resources:
# ping_gw
   - resource_id: 'ping_gw'
     action: 'create'
     provider: 'ocf:pacemaker:ping'
     options:
       - 'host_list=78.128.211.1'       # adresa gw
     op: 'monitor'
     op_options:
       - 'interval=20'
       - 'on-fail=standby'

# standby ip adresa
   - resource_id: 'standby_ip'
     action: 'create'
     provider: 'ocf:heartbeat:IPaddr2'
     options:
       - 'ip=78.128.211.53'
       - 'nic=eth0'
       - 'cidr_netmask=24'
     meta:
       - 'migration-threshold=1'
       - 'failure-timeout=300'
     op: 'monitor'
     op_options:
       - 'interval=30'
       - 'timeout=30'
       - 'on-fail=restart'

# offline file
   - resource_id: 'offline_file'
     action: 'create'
     provider: 'systemd:offline_file'
     meta:
       - 'migration-threshold=1'
       - 'failure-timeout=300'
     op: 'monitor'
     op_options:
       - 'interval=30'
       - 'timeout=30'
       - 'on-fail=restart'

# racoon
   - resource_id: 'racoon'
     action: 'create'
     provider: 'systemd:racoon'
     meta:
       - 'migration-threshold=1'
       - 'failure-timeout=300'
     op: 'monitor'
     op_options:
       - 'interval=30'
       - 'timeout=30'
       - 'on-fail=restart'

# radiator
   - resource_id: 'radiator'
     action: 'create'
     provider: 'systemd:radiator'
     meta:
       - 'migration-threshold=1'
       - 'failure-timeout=300'
     op: 'monitor'
     op_options:
       - 'interval=30'
       - 'timeout=30'
       - 'on-fail=restart'

# mailto
   - resource_id: 'mailto'
     action: 'create'
     provider: 'ocf:heartbeat:MailTo'
     options:
       - 'email=machv@cesnet.cz'
     op: 'monitor'
     op_options:
       - 'interval=30'
       - 'timeout=30'
       - 'on-fail=restart'

# klonovane zdroje
pacemaker_cluster_cloned_resources:
  - resource_id: 'ping_gw'

# zdroje ktere maji byt v jedne skupine
pacemaker_cluster_grouped_resources:
  - resource_id: 'standby_ip'
  - resource_id: 'offline_file'
  - resource_id: 'racoon'
  - resource_id: 'radiator'
  - resource_id: 'mailto'

# ============================================================
pacemaker_cluster_constraints:
# konfigurace omezeni

# poradi ve skupine je dano poradim, ve kterem jsou zdroje definovany

# omezeni kde me skupina primarne bezet
   - constraint: 'location'
     action: 'add'
     name: 'group_pref'
     resource_id: '{{ pacemaker_group_name }}'
     score: '50'
     target_node: '{{ master_server }}'

# omezeni pro pripad, ze uzel nebude mit konektivitu
   - constraint: 'location'
     action: 'rule'
     name: 'no_ping'
     resource_id: '{{ pacemaker_group_name }}'
     score: '-INFINITY'
     rule: 'not_defined pingd or pingd lte 0'

# ============================================================
# konfigurace vlastnosti clusteru
# http://clusterlabs.org/doc/en-US/Pacemaker/1.1/html/Pacemaker_Explained/s-cluster-options.html

pacemaker_cluster_settings:
   - property: 'stonith-enabled'
     value: 'no'
   - property: 'no-quorum-policy'
     value: 'ignore'
   - property: 'default-resource-stickiness'
     value: '100'

# ============================================================
