- name: install necessary packages
  apt:
    name: "{{ item }}"
    state: "present"
  with_items:
    - 'pacemaker'
    - 'crmsh'
    - 'corosync'
    - 'pacemaker-cli-utils'
    - 'pacemaker-resource-agents'
    - 'pacemaker-common'
