- name: check pacemaker status
  command: crm status
  register: _crm_status
  
- name: print pacemaker status
  debug:
    var: _crm_status.stdout_lines

#- name: configure pacemaker
#  template:
#    src: "etc/corosync/corosync.conf.j2"
#  register: "_pacemaker_configured"


