- name: copy offline_file script
  template:
    src: "usr/local/bin/offline_file.sh.j2"
    dest: "/usr/local/bin/offline_file.sh"
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rx,o=rx"

- name: copy offline_file startup file
  template:
    src: "etc/systemd/system/offline_file.service.j2"
    dest: "/etc/systemd/system/offline_file.service"
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rx,o=rx"

- name: enable offline_file systemd service
  systemd:
    name: offline_file
    enabled: yes

# starup file racoona je vytvoren v /lib/systemd/system/racoon.service pri instalaci
# podle man racoon je defaultne cteny konfiguracni soubor v /etc/racoon.conf
# ackoliv /etc/racoon/racoon.conf take existuje
#
# parametry pro spusteni racoona pouzite ve startup filu se berou z /etc/racoon/racoon.conf
# nastaveni konfiguracniho souboru:
#RACOON_ARGS="-f /etc/racoon/racoon.conf"
#
- name: enable racoon systemd service
  systemd:
    name: racoon
    enabled: yes
