- name: copy offline_file script
  template:
    src: "usr/local/bin/offline_file.sh.j2"
    dest: "/usr/local/bin/offline_file.sh"
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rx,o=rx"

- name: copy offline_file startup file
  template:
    src: "etc/systemd/system/offline_file.service.j2"
    dest: "/etc/systemd/system/offline_file.service"
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rx,o=rx"

- name: enable offline_file systemd service
  systemd:
    name: offline_file
    enabled: yes

# originalni startup file je v debianu v /lib/systemd/system/racoon.service
# modifikovano tak, aby systemd vytvoril pid soubor
- name: copy racoon startup file
  template:
    src: "lib/systemd/system/racoon.service.j2"
    dest: "/lib/systemd/system/racoon.service"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"

# parametry pro spusteni racoona pouzite ve startup filu se berou z /etc/default/racoon
# nastaveni konfiguracniho souboru:
#RACOON_ARGS="-f /etc/racoon/racoon.conf"
- name: copy racoon default config
  template:
    src: "etc/default/racoon.j2"
    dest: "/etc/default/racoon"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"

- name: enable racoon systemd service
  systemd:
    name: racoon
    enabled: yes

- name: copy radiator startup file
  template:
    src: "etc/systemd/system/radiator.service.j2"
    dest: "/etc/systemd/system/radiator.service"
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rx,o=rx"

- name: enable radiator systemd service
  systemd:
    name: radiator
    enabled: yes
