
- name: pacemaker commit ###commented out for now...broken in ansible 2.0
  pacemaker: commit

- name: restart corosync
  service:
    name: "corosync"
    state: "restarted"
  become: true

- name: restart pacemaker
  service:
    name: "pacemaker"
    sleep: 10
    state: "restarted"
  become: true

- name: config | Ensuring Service Are Enabled
  service:
    name: "{{ item }}"
    enabled: true
  become: true
  with_items:
    - 'corosync'
    - 'pacemaker'
    - 'pcsd'
