# ============================================================
# konfiguracni promenne pro corosync a pacemaker

corosync_authkey_file: '/etc/corosync/authkey'
corosync_config_file: '/etc/corosync/corosync.conf'
corosync_expected_votes: 2
corosync_transport_proto: 'udpu'
corosync_crypto_cipher: 'aes256'
corosync_crypto_hash: 'sha256'
corosync_two_node: true
#corosync_last_man_standing: true	# https://www.systutorials.com/docs/linux/man/5-votequorum/
#corosync_wait_for_all: true		# https://www.systutorials.com/docs/linux/man/5-votequorum/
pacemaker_disable_stonith: true

