# ============================================================
# konfiguracni promenne pro corosync a pacemaker

master_server: 'r1nren.et.cesnet.cz'
corosync_authkey_file: '/etc/corosync/authkey'
corosync_config_file: '/etc/corosync/corosync.conf'
corosync_expected_votes: 2
corosync_cluster_name: 'debian'
corosync_transport_proto: 'udpu'
corosync_crypto_cipher: 'aes256'
corosync_crypto_hash: 'sha256'
corosync_two_node: true
#corosync_last_man_standing: true	# https://www.systutorials.com/docs/linux/man/5-votequorum/
#corosync_wait_for_all: true		# https://www.systutorials.com/docs/linux/man/5-votequorum/
pacemaker_disable_stonith: true

# ============================================================
# konfigurace clusteru

# ============================================================
# konfigurace zdroju

# manualni smazani konfigurace celeho clusteru
# # cibadmin -E --force

pacemaker_cluster_resources:

# standby ip adresa
# man ocf_heartbeat_IPaddr2
   - resource_id: 'standby_ip'
     action: 'create'
     provider: 'ocf:heartbeat:IPaddr2'
     options:
       - 'ip=78.128.211.53'
       - 'nic=eth0'
       - 'cidr_netmask=24'
       # arp_count_refresh
       # arp_sender
     meta:
       - 'migration-threshold=1'
       - 'failure-timeout=300'
     op: 'monitor'
     op_options:
       - 'interval=60'
       - 'timeout=300'
       - 'on-fail=restart'

# TODO - pri zmene parametru bude vytvoren dalsi zdroj nebo budou tomuhle jen zmeneny parametry?

# offline file
   - resource_id: 'offline_file'
     action: 'create'
     #provider: 'lsb:offline_file'
     provider: 'systemd:offline_file'
     meta:
       - 'migration-threshold=1'
       - 'failure-timeout=300'
     op: 'monitor'
     op_options:
       - 'interval=60'
       - 'timeout=300'
       - 'on-fail=restart'

# racoon
   - resource_id: 'racoon'
     action: 'create'
     #provider: 'lsb:racoon'
     provider: 'systemd:racoon'
     meta:
       - 'migration-threshold=1'
       - 'failure-timeout=300'
     op: 'monitor'
     op_options:
       - 'interval=60'
       - 'timeout=300'
       - 'on-fail=restart'

# radiator
   - resource_id: 'radiator'
     action: 'create'
     #provider: 'lsb:radiator'
     provider: 'systemd:radiator'
     meta:
       - 'migration-threshold=1'
       - 'failure-timeout=300'
     op: 'monitor'
     op_options:
       - 'interval=60'
       - 'timeout=300'
       - 'on-fail=restart'

# ============================================================
# konfigurace omezeni

pacemaker_cluster_constraints:

# zavislosti zdroju
   - constraint: 'colocation'
     action: 'add'
     source_resource_id: 'offline_file'
     target_resource_id: 'standby_ip'
     score: 'INFINITY'
   - constraint: 'colocation'
     action: 'add'
     source_resource_id: 'racoon'
     target_resource_id: 'offline_file'
     score: 'INFINITY'
   - constraint: 'colocation'
     action: 'add'
     source_resource_id: 'radiator'
     target_resource_id: 'offline_file'
     score: 'INFINITY'

# preference zdroju
   - constraint: 'location'
     action: 'add'
     name: 'ip_pref'
     resource_id: 'standby_ip'
     score: '50'
     target_node: '{{ master_server }}'
   - constraint: 'location'
     action: 'add'
     name: 'offline_file_pref'
     resource_id: 'offline_file'
     score: '50'
     target_node: '{{ master_server }}'
   - constraint: 'location'
     action: 'add'
     name: 'racoon_pref'
     resource_id: 'racoon'
     score: '50'
     target_node: '{{ master_server }}'
   - constraint: 'location'
     action: 'add'
     name: 'radiator_pref'
     resource_id: 'radiator'
     score: '50'
     target_node: '{{ master_server }}'

   #- constraint: 'order'
   #  order:
   #    first_resource: 'virtual_ip'
   #    first_resource_action: 'start'
   #    second_resource: 'webserver'
   #    second_resource_action: 'start'

# ============================================================
# konfigurace vlastnosti clusteru

pacemaker_cluster_settings:
   - property: 'stonith-enabled'
     value: 'no'
   - property: 'no-quorum-policy'
     value: 'ignore'
   - property: 'default-resource-stickiness'
     value: '100'

   # TODO ?
   #- property: 'start-failure-is-fatal'
   #  value: 'false'
   #- property: 'pe-warn-series-max'
   #  value: 1000
   #- property: 'pe-input-series-max'
   #  value: 1000
   #- property: 'pe-error-series-max'
   #  value: 1000
   #- property: 'cluster-recheck-interval'
   #  value: 5min

# ============================================================
# dodatecne poznamky
#
# zajimavy agent - https://github.com/ClusterLabs/resource-agents/blob/master/heartbeat/MailTo
# -> generuje mail pri migraci zdroju
#
#
#
#
#
#
#


# poznamka z clusters from scratch:
# Do not accept the default network settings. Cluster machines should never obtain an IP address
# via DHCP, because DHCP’s periodic address renewal will interfere with corosync.

# resource options:
# http://clusterlabs.org/doc/en-US/Pacemaker/1.1/html/Pacemaker_Explained/s-resource-options.html


# zdroje:
#
# firewall neni treba jako zdroj
# ipsec politiky take ne
#
# poradi:
# standby_ip, offline_file, racoon, radiator
#
#
# racoon a radiator muzou byt paralelne
#
# pridat ping na gw jako zdroj?
