- name: install necessary packages
  apt:
    name: "{{ item }}"
    state: "present"
  with_items:
    - 'pacemaker'
    - 'crmsh'
    - 'corosync'
    - 'pacemaker-cli-utils'
    - 'pacemaker-resource-agents'
    - 'pacemaker-common'
    - 'postfix'         # TODO - instalovat i na produkci?
    - 'mailutils'       # TODO - instalovat i na produkci?

# provadet na produkci?
- name: Set Postfix option type as internet site
  debconf: name=postfix question="postfix/main_mailer_type" value="'Internet Site'" vtype="string"

# provadet na produkci?
- name: Set Postfix option hostname
  debconf: name=postifx question="postfix/mailname" value="{{ inventory_hostname }}" vtype="string"
