# ===================================================
# instalace potrebnych baliku
- name: install necessary packages
  apt:
    name: "{{ item }}"
    state: "present"
  with_items:
    - 'pacemaker'
    - 'crmsh'
    - 'corosync'
    - 'pacemaker-cli-utils'
    - 'pacemaker-resource-agents'
    - 'pacemaker-common'
#    - 'postfix'         # na prudukci je manualne instalovany exim4
    - 'mailutils'

# # provadet na produkci?
# - name: Set Postfix option type as internet site
#   debconf: name=postfix question="postfix/main_mailer_type" value="'Internet Site'" vtype="string"

# # provadet na produkci?
# - name: Set Postfix option hostname
#   debconf: name=postifx question="postfix/mailname" value="{{ inventory_hostname }}" vtype="string"

# ===================================================
# povoleni managementu sluzeb spravucjicich cluster operacnim systemem

- name: enable pacemaker systemd service
  systemd:
    name: pacemaker
    enabled: yes

- name: enable corosync systemd service
  systemd:
    name: corosync
    enabled: yes
