---
# ===================================================
# promenna ONLINE znaci master server:
# ONLINE == True => master
# ONLINE == False => slave

- include: determine_master.yml
- include: install.yml
- include: services.yml
- include: disable_slave.yml
  when: not ONLINE
- include: corosync.yml
- include: cluster.yml
  when: ONLINE
- include: enable_slave.yml
  when: not ONLINE
