# ===================================================
# offline_file
- name: copy offline_file script
  template:
    src: "usr/local/bin/offline_file.sh.j2"
    dest: "/usr/local/bin/offline_file.sh"
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rx,o=rx"

- name: copy offline_file startup file
  template:
    src: "etc/systemd/system/offline_file.service.j2"
    dest: "/etc/systemd/system/offline_file.service"
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rx,o=rx"

# ===================================================
# racoon

# originalni startup file je v debianu v /lib/systemd/system/racoon.service
# modifikovano tak, aby systemd vytvoril pid soubor
- name: copy racoon startup file
  template:
    src: "lib/systemd/system/racoon.service.j2"
    dest: "/lib/systemd/system/racoon.service"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"

# parametry pro spusteni racoona pouzite ve startup filu se berou z /etc/default/racoon
# nastaveni konfiguracniho souboru:
#RACOON_ARGS="-f /etc/racoon/racoon.conf"
- name: copy racoon default config
  template:
    src: "etc/default/racoon.j2"
    dest: "/etc/default/racoon"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"

# ===================================================
# radiator

- name: copy radiator startup file
  template:
    src: "etc/systemd/system/radiator.service.j2"
    dest: "/etc/systemd/system/radiator.service"
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rx,o=rx"

# ===================================================
# eduroam_ping

- name: copy eduroam_ping startup file
  template:
    src: "etc/systemd/system/eduroam_ping.service.j2"
    dest: "/etc/systemd/system/eduroam_ping.service"
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rx,o=rx"

- name: copy eduroam_ping script
  template:
    src: "usr/local/bin/eduroam_ping.sh.j2"
    dest: "/usr/local/bin/eduroam_ping.sh"
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rx,o=rx"

# ===================================================
# zakazani managementu clusterovanych sluzeb operacnim systemem

# clusters from scratch: "Services that are intended to be managed via the cluster software should never be managed by the OS."

- name: disable radiator systemd service
  systemd:
    name: radiator
    enabled: no

- name: disable offline_file systemd service
  systemd:
    name: offline_file
    enabled: no

- name: disable racoon systemd service
  systemd:
    name: racoon
    enabled: no

# eduroam_ping neni(nebyl) povolen, ale presto je zakazan
- name: disable eduroam_ping systemd service
  systemd:
    name: eduroam_ping
    enabled: no

# ===================================================
# preventivni vypnuti vsech sluzeb na slave uzlu
# tim se zamezi(?) vzniku stavu, kdy bude cela skupina
# spustena na slave uzlu

# tohle bohuzel neni dostatecne, protoze ostatni "sluzby"
# zustanou bezet
# TODO - da se to nejak vyresit?

- name: disable all clustered systemd services
  systemd:
    name: "{{ item }}"
    state: stopped
  with_items:
    - 'offline_file'
    - 'racoon'
    - 'radiator'
    - 'eduroam_ping'
  when: inventory_hostname != master_server

# ===================================================
# povoleni managementu sluzeb spravucjicich cluster operacnim systemem

- name: enable pacemaker systemd service
  systemd:
    name: pacemaker
    enabled: yes

- name: enable corosync systemd service
  systemd:
    name: corosync
    enabled: yes
